export default [
    {
        path:'/home',
        name:'home',
        label:'Home',
        icon:'HomeOutlined',
        url:'/home/home'
    },
    {
        path:'/item',
        name:'item',
        label:'Item',
        icon:'AppleOutlined',
        url:'/item/item'
    },
    {
        path:'/store',
        name:'store',
        label:'Store',
        icon:'ShopOutlined',
        url:'/store/store'
    },
    {
        path:'/profile',
        label:'Profile',
        icon:'SettingOutlined',
        url:'/profile/Profile'
    }
]